=== Akello32/10_JavaST_2020_Task-/part02.task04.XML/src/main/resources/tourism.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema attributeFormDefault="unqualified"
        elementFormDefault="qualified"
        xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://matmux.by/tourism"
        xmlns:tns="http://matmux.by/tourism">
    <element name="touristVouchers">
        <complexType>
            <sequence>
                <element name="touristVoucher" type="tns:Tourism"
                         minOccurs="1"
                         maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>

    <complexType name="Tourism">
        <sequence>
            <element name="date" type="date"/>
            <element name="days" type="int"/>
            <element name="cost" type="int"/>
            <element name="transport" type="tns:Transport"/>
            <element name="hotel" type="tns:Hotel"/>
        </sequence>
        <attribute name="nameVouchers" type="tns:Name" use="required"/>
        <attribute name="country">
            <simpleType>
                <restriction base="string">
                    <enumeration value="ENG"/>
                    <enumeration value="RUS"/>
                    <enumeration value="BY"/>
                    <enumeration value="USA"/>
                    <enumeration value="UA"/>
                </restriction>
            </simpleType>
        </attribute>
    </complexType>

    <simpleType name="Name">
        <restriction base="ID">
            <pattern value=" "/>
        </restriction>
    </simpleType>

    <complexType name="Transport">
        <sequence>
            <element name="type" type="string"/>
            <element name="brand" type="string"/>
            <element name="yearOfManufacture" type="string"/>
        </sequence>
    </complexType>

    <complexType name="Hotel">
        <sequence>
            <element name="rating" type="int"/>
            <element name="meals" type="string"/>
            <element name="room" type="tns:Room"/>
        </sequence>
    </complexType>

    <complexType name="Room">
        <sequence>
            <element name="TV" type="boolean"/>
            <element name="conditioner" type="boolean"/>
        </sequence>
        <attribute name="typeRoom" use="optional" default="Coach"/>
        <attribute name="persons" use="required"/>
    </complexType>
</schema>

=== Akello32/10_JavaST_2020_Task-/part02.task04.XML/src/main/resources/tourism.xml
<?xml version="1.0" encoding="UTF-8"?>

<touristVouchers xmlns="http://matmux.by/tourism"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://matmux.by/tourism tourism.xsd">
    <touristVoucher nameVoucher="FFF" country="ENG">
        <date>2021-02-12</date>
        <days>2</days>
        <cost>500</cost>
        <airplane>
            <brand>SuperJet</brand>
            <yearOfManufacture>2020</yearOfManufacture>
            <seat>10</seat>
            <airlines>BelAvia</airlines>
        </airplane>
        <hotel>
            <rating>3</rating>
            <meals>BB</meals>
            <room typeRoom="LUX" persons="3">
                <TV>true</TV>
                <conditioner>false</conditioner>
            </room>
        </hotel>
    </touristVoucher>
        <touristVoucher nameVoucher="AAA" country="RUS">
        <date>2022-01-10</date>
        <days>5</days>
        <cost>600</cost>
        <train railwayCar="business-class">
            <brand>AN-500</brand>
            <yearOfManufacture>1990</yearOfManufacture>
        </train>
        <hotel>
            <rating>3</rating>
            <meals>BB</meals>
            <room typeRoom="LUX" persons="3">
                <TV>true</TV>
                <conditioner>false</conditioner>
            </room>
        </hotel>
    </touristVoucher>
</touristVouchers>
